# invoke the dockerfile to build the image
version: '3.8'

services:
  nginx:
    build: 
      context: ./
      dockerfile: ./loadBalancer/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - my-network
    restart: always

  psql:
    image: postgres:15.3
    environment:
    # set username and password
      POSTGRES_USER: zomerProject
      POSTGRES_PASSWORD: Passw0rd
      TZ: 'Europe/Amsterdam'
      PGTZ: 'Europe/Amsterdam'
    ports:
      - "5432:5432"
    volumes:
      - ./database/psql_data:/var/lib/postgresql/data
      - ./database/structure.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - my-network
    restart: always

  nodejs:
    build: /nodeJS
    ports:
      - "3000:8080"
    networks:
      - my-network
    restart: always

  python:
    build: /python
    ports:
      - "3001:8080"
    networks:
      - my-network
    restart: always

networks:
  my-network:
    driver: bridge